version: "3.7"

services:
  api:
    image: python-app
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      FLASK_ENV: development
    labels:
      traefik.enable: true
      traefik.http.routers.nginx1.rule: PathPrefix(`/api`)
      traefik.port: 3000

  app:
    image: vtcs2304s19/blabber-client
    # working_dir: /app
    # volumes:
    #   - ./:/app
    # ports:
    #   - 3000:3000
    # environment:
    #   FLASK_ENV: development
    labels:
      traefik.http.routers.nginx2.rule: Path(`/`)
      traefik.port: 80

  mongo:
    image: mongo

  # tests:
  #   image: vtcs2304s19/blabber-api-tests
  #   environment:
  #     SERVICE_NAME: api
  #     API_PORT: "5000"

  proxy:
    image: traefik:v2.1
    command: --api.insecure=true --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
